[package]
name = "seadog-scheduler"
version = "0.1.0"
authors = ["hypnoes <liumulei@icloud.com>"]
edition = "2024"

[[bin]]
name = "seadog-scheduler"
path = "src/main.rs"

[dependencies]
uuid = { version = "1.18.1", features = ["v4"] }
